In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
values=[20.1,20.4,12.3,43.5,54.4,23.5]

In [13]:
values.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [5]:
import numpy as np

In [6]:
import numpy as np
convert=np.array(values)
print(convert)
print(convert+20)

[20.1 20.4 12.3 43.5 54.4 23.5]
[40.1 40.4 32.3 63.5 74.4 43.5]


In [7]:
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [12]:
a.ndim

2

In [8]:
a=np.array([1,2,3],dtype=float)
print(a)

[1. 2. 3.]


In [9]:
a=np.array([[1,2,3],[4,5,6]],dtype=float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [10]:
a.ndim

2

In [11]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [14]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
a.ndim

[1 2 3 4 5 6 7 8 9]


1

In [15]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
a.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


3