In [23]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [24]:
values=[20.1,20.4,12.3,43.5,54.4,23.5]

In [25]:
values.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [ ]:
import numpy as np

In [26]:
import numpy as np
convert=np.array(values)
print(convert)
print(convert+20)

[20.1 20.4 12.3 43.5 54.4 23.5]
[40.1 40.4 32.3 63.5 74.4 43.5]


In [27]:
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [28]:
a.ndim

1

In [29]:
a=np.array([1,2,3],dtype=float)
print(a)

[1. 2. 3.]


In [30]:
a=np.array([[1,2,3],[4,5,6]],dtype=float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [31]:
a.ndim

2

In [32]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [33]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
a.ndim

[1 2 3 4 5 6 7 8 9]


1

In [34]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
a.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

In [35]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [36]:
a.shape

(1, 3, 3)

In [37]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [38]:
a.dtype

dtype('int32')

Accessing / Changing specific elements, rows, columns, etc.

In [39]:
import numpy as np

In [41]:
a=np.array([[1,2,3,4,5,6,7,8,9],[8,9,10,11,12,13,14,15,16]])
print(a)

[[ 1  2  3  4  5  6  7  8  9]
 [ 8  9 10 11 12 13 14 15 16]]


In [42]:
a.ndim

2

In [43]:
a.shape

(2, 9)

In [44]:
#getting a specific element in [rows,columns] --> index number will start from 0.
a[0,6]

7

In [45]:
a[1,8]

16

In [48]:
a[1,9] #this arrise error due to we are calling 9th element which is true, we have 9 element but index will start from 0. so basically we are calling 10th element. that's why, it arises error. 

IndexError: index 9 is out of bounds for axis 1 with size 9

In [49]:
a[2,0]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [50]:
a[0,-1]

9

In [51]:
 #if we have to call specific rows all element then use this
a[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16])

In [53]:
a[-1,-1]

16

In [54]:
a[-1,-2]

15

In [55]:
a[:,2]

array([ 3, 10])

In [56]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [57]:
#to change and specific element in rows and columns
a[0,5]=9
a

array([[ 1,  2,  3,  4,  5,  9,  7,  8,  9],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16]])

Zeros/Ones Method in Numpy 

In [58]:
b=np.zeros((3,3))  #(rows, columns) this will give in float type.
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
c=np.ones((4,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
#change float datatype to int data type
b=np.zeros((3,3),dtype='int32') 
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [61]:
 a=np.full((3,3), 50, dtype='int')
a

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [64]:
np.random.rand(4,4)

array([[0.60925148, 0.69774434, 0.15329842, 0.53513007],
       [0.7698191 , 0.19067852, 0.59774287, 0.12833764],
       [0.02177133, 0.78581049, 0.58339654, 0.27057689],
       [0.83389185, 0.29767173, 0.50121669, 0.90947211]])

In [65]:
np.random.randint(-4,1,size=(3,3))

array([[-1, -1, -1],
       [-4, -2, -4],
       [-3, -3, -2]])

In [68]:
np.identity(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Practice Questions

Extract all the first 3 rows of the last 5 columns in a given numpy 2D array 'a'?

In [69]:
a=np.array([[1,2,3,4,5,6],
           [10,20,30,40,50,60],
            [12,12,12,11,21,12],
            [11,11,11,11,11,11],
            [45,45,45,45,45,45]])

In [70]:
a[:3, -5:]  #or a[0:3, -5:-1]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 11, 21, 12]])

In [78]:
n=5

In [79]:
import numpy as np

In [80]:
#create an (n*n) array with all zeros
z=np.zeros((n,n),dtype='int')
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [81]:
5//2

2

In [82]:
#make the middle row and column all 1's
z[n//2,:]=1
z[:,n//2]=1

z

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])