In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [2]:
df = pd.read_csv('spam.csv')

In [3]:
df.head(5)

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df.Category.value_counts()/len(df)*100

Category
ham     86.593683
spam    13.406317
Name: count, dtype: float64

In [6]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [7]:
df.head(5)

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [8]:
new_df = pd.read_csv('spam.csv')

In [9]:
new_df['Category'].replace({'ham':0,'spam':1}, inplace=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_1560\2701969205.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['Category'].replace({'ham':0,'spam':1}, inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_1560\2701969205.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df['Category'

In [10]:
new_df.head(5)

,Category,Message
0,0,"Go until jurong point, crazy.. Available only ..."
1,0,Ok lar... Joking wif u oni...
2,1,Free entry in 2 a wkly comp to win FA Cup fina...
3,0,U dun say so early hor... U c already then say...
4,0,"Nah I don't think he goes to usf, he lives aro..."


In [11]:
df.head(5)

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [12]:
df.shape

(5572, 3)

#### **Train Test Split**

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam,test_size=0.2)

In [14]:
X_train.shape

(4457,)

In [15]:
X_test.shape

(1115,)

In [16]:
X_train[:4]

3632               Thank you princess! You are so sexy...
4516    That was random saw my old roomate on campus. ...
5342    u r subscribed 2 TEXTCOMP 250 wkly comp. 1st w...
850     Today's Offer! Claim ur £150 worth of discount...
Name: Message, dtype: object

In [17]:
y_train[:4]

3632    0
4516    0
5342    1
850     1
Name: spam, dtype: int64

#### **Create bag of words representation using CountVectorizer**

In [18]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_test_cv = v.transform(X_test)

In [19]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59030 stored elements and shape (4457, 7679)>

In [20]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7679,))

In [21]:
X_train_cv.shape

(4457, 7679)

In [22]:
v.get_feature_names_out()[1771]

'ciao'

In [23]:
v.vocabulary_

{'thank': 6728,
 'you': 7636,
 'princess': 5339,
 'are': 1027,
 'so': 6210,
 'sexy': 5971,
 'that': 6737,
 'was': 7313,
 'random': 5498,
 'saw': 5850,
 'my': 4588,
 'old': 4851,
 'roomate': 5744,
 'on': 4857,
 'campus': 1589,
 'he': 3304,
 'graduated': 3167,
 'subscribed': 6492,
 'textcomp': 6717,
 '250': 354,
 'wkly': 7489,
 'comp': 1878,
 '1st': 320,
 'wk': 7486,
 'free': 2935,
 'question': 5458,
 'follows': 2873,
 'subsequent': 6497,
 'wks': 7491,
 'charged': 1694,
 '150p': 288,
 'msg': 4537,
 'unsubscribe': 7105,
 'txt': 7017,
 'stop': 6424,
 '84128': 659,
 'custcare': 2080,
 '08712405020': 101,
 'today': 6864,
 'offer': 4824,
 'claim': 1778,
 'ur': 7126,
 '150': 286,
 'worth': 7537,
 'of': 4820,
 'discount': 2295,
 'vouchers': 7250,
 'text': 6713,
 'yes': 7620,
 'to': 6859,
 '85023': 663,
 'now': 4765,
 'savamob': 5845,
 'member': 4366,
 'offers': 4827,
 'mobile': 4469,
 'cs': 2046,
 '08717898035': 125,
 '00': 0,
 'sub': 6485,
 '16': 300,
 'unsub': 7104,
 'reply': 5643,
 'come': 1

In [24]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7679,))

In [25]:
np.where(X_train_np[0]!=0)

(array([1027, 5339, 5971, 6210, 6728, 7636]),)

#### **Naive Bayes Classifier**

In [26]:
model = MultinomialNB()
model.fit(X_train_cv, y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [27]:
y_pred = model.predict(X_test_cv)

In [28]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       955
           1       0.97      0.94      0.96       160

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



#### **Test on a random datapoint**

In [29]:
message = {"Upto 20% off on parking, exclusing offer just for you"}

In [30]:
message_cnt = v.transform(message)

model.predict(message_cnt)

array([1])