In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Mounting the google colab drive
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# Importing the dataset
dataset = pd.read_csv('churnModelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
# Showing the first 5 rows
dataset.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0


In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [5]:
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [6]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], shape=(10000, 10), dtype=object)

In [7]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
len(dataset)

10000

In [9]:
len(X_test)

2000

In [10]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
#Classical ML

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
pred = clf.predict(X_test)

In [12]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred)

print(cm)

[[1362  233]
 [ 190  215]]


In [13]:
# Making the Confusion Matrix
from sklearn.metrics import accuracy_score

score = accuracy_score(y_test,pred)
print(score*100)

78.85


### Accuracy from Decision Tree Classifier: 80%

In [14]:
## Random Forest

#Classical ML

from sklearn.ensemble import RandomForestClassifier
clf2 = RandomForestClassifier(n_estimators=200)
clf2.fit(X_train, y_train)
pred2 = clf2.predict(X_test)

In [15]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test, pred2)

print(cm2)

[[1520   75]
 [ 203  202]]


In [16]:
# Making the Confusion Matrix
from sklearn.metrics import accuracy_score

score2 = accuracy_score(y_test,pred2)
print(score2*100)

86.1


### Accuracy from Random Forest Classifier: 87%

# ANN - Let's get started!!

In [19]:
!pip install keras
!pip install tensorflow

   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------------------------- -------------- 1.0/1.6 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 9.6 MB/s  0:00:00

   -------- ------------------------------- 1/5 [optree]
   ------------------------ --------------- 3/5 [absl-py]
   -------------------------------- ------- 4/5 [keras]
   -------------------------------- ------- 4/5 [keras]
   -------------------------------- ------- 4/5 [keras]
   -------------------------------- ------- 4/5 [keras]
   -------------------------------- ------- 4/5 [keras]
   -------------------------------- ------- 4/5 [keras]
   -------------------------------- ------- 4/5 [keras]
   -------------------------------- ------- 4/5 [keras]
   -------------------------------- ------- 4/5 [keras]
   -------------------------------- ------- 4/5 [keras]
   -------------------------------- ------- 4/5 [keras]
   -------------------------------- ------- 4/5 [k

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.51.0 requires protobuf<7,>=3.20, but you have protobuf 7.34.1 which is incompatible.


In [20]:
# Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [21]:
# Initialising the ANN
classifier = Sequential()
#units: It's an art, comes by experience, input+output/2
#initializer: how your weights are updated
#relu activation function
#input_dim: input shape (shape of the data, how many features do we have in the data)
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the third  hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

C:\Users\Dell\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [22]:
len(X_train)

8000

In [23]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
y_train[0]
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 50)

Epoch 1/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7956 - loss: 0.5441
Epoch 2/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7960 - loss: 0.5063
Epoch 3/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7960 - loss: 0.5063
Epoch 4/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7960 - loss: 0.5063
Epoch 5/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7960 - loss: 0.5061
Epoch 6/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7960 - loss: 0.5062
Epoch 7/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7960 - loss: 0.5062
Epoch 8/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7960 - loss: 0.5062
Epoch 9/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7960 - loss: 0.5062
Epoch 10/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7960 - loss: 0.5064
Epoch 11/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7960 - loss: 0.5063
Epoch 12/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

In [24]:
# Part 3 - Making predictions and evaluating the model
# Predicting the Test set results
y_pred_ann = classifier.predict(X_test)
y_pred_ann = (y_pred_ann > 0.5)

cm3 = confusion_matrix(y_test, y_pred_ann)
print(cm3)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[1595    0]
 [ 405    0]]


In [25]:
# Making the Confusion Matrix
from sklearn.metrics import accuracy_score

score3 = accuracy_score(y_test,y_pred_ann)
print(score3*100)

79.75


### Accuracy from ANN: 84%

## Conclusion:

So, as we have already seen, by using 2 hidden layered ANN, we aren't able to get beyond 85% accuracy, ofcourse we can get higher accuracy by increasing the epochs & doing some hyperparameter tuning, so on the other hand, the classical models can also be tuned further.

Bottomline, always start with classical machine learning models, and if we aren't able to increase the performance, then move towards Deep Learning techniques :)

# Hyper Parameter Tuning - Run at your own risk 👍👍




In [26]:
# Predicting a single new observation
"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""
new_prediction = classifier.predict(sc.transform(np.array([[600, 0, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = (new_prediction > 0.5)
new_prediction
# Making the Confusion Matrix
#from sklearn.metrics import confusion_matrix
#cm = confusion_matrix(y_test, y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[False]])

In [27]:
#Importing few libraries for k-folds
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)

accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv =10, n_jobs = -1 )
mean1 = accuracies.mean()
variance = accuracies.std()

ModuleNotFoundError: No module named 'keras.wrappers.scikit_learn'

In [32]:
# First, install the scikeras package
!pip install scikeras

# After installation, import the necessary libraries
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

# Updated KerasClassifier initialization for scikeras
classifier = KerasClassifier(model=build_classifier, batch_size=10, epochs=10)

accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv=10, n_jobs=-1)
mean1 = accuracies.mean()
variance = accuracies.std()

ValueError: 
All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1501, in fit
    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 770, in fit
    self._fit(
    ~~~~~~~~~^
        X=X,
        ^^^^
    ...<3 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\Dell\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 925, in _fit
    X, y = self._initialize(X, y)
           ~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Dell\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 853, in _initialize
    X, y = self._validate_data(X, y, reset=True)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 626, in _validate_data
    X, y = check_X_y(
           ~~~~~~~~~^
        X,
        ^^
    ...<4 lines>...
        dtype=None,
        ^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1314, in check_X_y
    X = check_array(
        X,
    ...<12 lines>...
        input_name="X",
    )
  File "C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1074, in check_array
    _assert_all_finite(
    ~~~~~~~~~~~~~~~~~~^
        array,
        ^^^^^^
    ...<2 lines>...
        allow_nan=ensure_all_finite == "allow-nan",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 133, in _assert_all_finite
    _assert_all_finite_element_wise(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        X,
        ^^
    ...<4 lines>...
        input_name=input_name,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 182, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.


In [33]:
variance

NameError: name 'variance' is not defined

In [34]:
# Define the variance variable before using it
variance = 0  # Initialize with an appropriate value

# Or if you intended to use NumPy's variance function:
import numpy as np
data = [1, 2, 3, 4, 5]  # Example data
variance = np.var(data)
print(variance)

2.0


In [35]:
accuracies

NameError: name 'accuracies' is not defined

In [36]:
# First, define the accuracies variable before trying to use it
# For example, you might want to initialize it as an empty list
accuracies = []

# Now you can use the variable
accuracies

[]

In [37]:
mean1

NameError: name 'mean1' is not defined

In [38]:
# First, define the accuracies variable before trying to use it
# For example, you might want to initialize it as an empty list
accuracies = []

# Now you can use the variable
accuracies

[]

In [39]:
#Improvising the ANN - Hyper parameter optimization

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense


def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier


classifier = KerasClassifier(build_fn = build_classifier)

parameters = {'batch_size': [10, 20],
              'epochs': [5, 6]}

              # Total combinations: 4

grid_search = GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', n_jobs = -1, cv = 5)
grid_search = grid_search.fit(X_train, y_train)
grid_search.best_params_
grid_search.best_score_

ModuleNotFoundError: No module named 'keras.wrappers.scikit_learn'

In [40]:
#Improvising the ANN - Hyper parameter optimization

# Updated import for KerasClassifier
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier  # Changed from keras to tensorflow.keras
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential  # Changed from keras to tensorflow.keras
from tensorflow.keras.layers import Dense  # Changed from keras to tensorflow.keras


def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier


classifier = KerasClassifier(build_fn = build_classifier)

parameters = {'batch_size': [10, 20],
              'epochs': [5, 6]}

              # Total combinations: 4

grid_search = GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', n_jobs = -1, cv = 5)
grid_search = grid_search.fit(X_train, y_train)
grid_search.best_params_
grid_search.best_score_

ModuleNotFoundError: No module named 'tensorflow.keras.wrappers.scikit_learn'

In [41]:
grid_search.best_params_

NameError: name 'grid_search' is not defined

In [ ]:
grid_search.best_score_

0.8256249999999999

In [ ]:
#Improvising the ANN - Hyper parameter optimization, adding more hyperparameters
######################################
######################################
######################################
######################################
#TO DO TASK
######################################
######################################
######################################
######################################

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
def build_classifier(loss, optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = loss, metrics = ['accuracy'])
    return classifier


classifier = KerasClassifier(build_fn = build_classifier)

parameters = {'batch_size': [10,20, 30, 50],
              'epochs': [10,50,100,200],
              'loss': ['binary_crossentropy', 'categorical_crossentropy'],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', n_jobs = -1, cv = 10)

grid_search = grid_search.fit(X_train, y_train)

In [ ]:
tuple1 = ([2,3,4],6,7)

In [ ]:
tuple1[0][1]=5

In [ ]:
tuple1

([2, 5, 4], 6, 7)

## Improvising the performance of ANN

1. Increasing the number of hidden layers
2. Increasing the number of epochs
3. Fine-tuning the parameters - optimizers, batch_size, epochs
4. Dropout regularization: Dropout(0.25)

Overfitting problem --> training accuracy increases, but test accuracy is low